# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    build:
        name: Build MyApp
        environment:
            vars:
                XCODE_PROJECT: MyApp.xcodeproj
                XCODE_SCHEME: MyApp
            xcode: 11.7
            cocoapods: default
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: '*'
                  include: true
                  source: true
            cancel_previous_builds: true
        scripts:
            - xcodebuild -list > $HOME/xcodebuild_list
            - xcodebuild build -project $XCODE_PROJECT -scheme $XCODE_SCHEME CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            - cat `ls -t "$TMPDIR"/*.log | head -n 1` > $HOME/build.log
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
            - $HOME/build.log
            - $HOME/xcodebuild_list
    pass:
        name: Pass
        scripts:
            - echo "Pass"
