# Check out https://docs.codemagic.io/getting-started/building-a-native-ios-app/ for more information
# Please review and update values in curly braces

workflows:
    ios-app:
        name: iOS App
        environment:
            vars:
                XCODE_PROJECT: "MyApp.xcodeproj"
            xcode: 11.7
            cocoapods: default
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: '*'
                    include: true
                    source: true
            cancel_previous_builds: true
        scripts:
            - xcodebuild -list
            - xcodebuild build -project $XCODE_PROJECT CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
